swagger: "2.0"
info:
  title: Marvo Game API
  description: Marvo Game 相关的API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: 876505905@qq.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /driver_survey/:
    post:
      tags:
      - driver_survey
      description: 提交用户填写的调查数据
      operationId: DriverSurveyController.Post
      parameters:
      - in: body
        name: body
        description: json数据
        required: true
        schema:
          $ref: '#/definitions/models.SurveyForm'
      responses:
        "201":
          description: '{int} models.DriverSurvey'
        "403":
          description: body is empty
  /driver_survey/{id}:
    get:
      tags:
      - driver_survey
      description: get DriverSurvey by id
      operationId: DriverSurveyController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DriverSurvey'
        "403":
          description: :id is empty
definitions:
  models.DriverSurvey:
    title: DriverSurvey
    type: object
    properties:
      Age:
        description: 年龄
        type: string
      CreatedAt:
        description: 创建时间
        type: integer
        format: int64
      Email:
        description: 邮箱
        type: string
      Game:
        description: 游戏
        type: string
      Id:
        type: integer
        format: int64
      Name:
        description: 年龄
        type: string
      Region:
        description: 地区/国家
        type: string
      Sexuality:
        description: 性别(female|male)
        type: string
      Suggest:
        description: 建议
        type: string
  models.Sexuality:
    title: Sexuality
    type: string
  models.SurveyForm:
    title: SurveyForm
    type: object
    properties:
      Age:
        description: 年龄
        type: string
      Email:
        description: 邮箱
        type: string
      Game:
        description: 游戏
        type: string
      Name:
        description: 年龄
        type: string
      Region:
        description: 地区/国家
        type: string
      Sexuality:
        $ref: '#/definitions/models.Sexuality'
        description: 性别(female|male)
      Suggest:
        description: 建议
        type: string
tags:
- name: driver_survey
  description: |
    数据收集相关API
