swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /driver_survey/:
    post:
      tags:
      - driver_survey
      description: 提交用户填写的调查数据
      operationId: DriverSurveyController.Post
      parameters:
      - in: sexuality
        name: sexuality
        description: 调查表单:性别 取值[male|female]
        required: true
        schema:
          $ref: '#/definitions/models.sexuality'
      - in: region
        name: region
        description: 调查表单:地区/国家
        required: true
        schema:
          $ref: '#/definitions/models.region'
      - in: email
        name: email
        description: 调查表单:邮箱
        required: true
        schema:
          $ref: '#/definitions/models.email'
      - in: suggest
        name: suggest
        description: 调查表单:建议
        schema:
          $ref: '#/definitions/models.suggest'
      - in: age
        name: age
        description: 调查表单:年龄
        schema:
          $ref: '#/definitions/models.age'
      - in: game
        name: game
        description: 调查表单:游戏名称
        schema:
          $ref: '#/definitions/models.game'
      responses:
        "201":
          description: 成功提交数据到服务
        "403":
          description: email is empty
  /driver_survey/{id}:
    get:
      tags:
      - driver_survey
      description: get DriverSurvey by id
      operationId: DriverSurveyController.Get One
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.DriverSurvey'
        "403":
          description: :id is empty
definitions:
  models.DriverSurvey:
    title: DriverSurvey
    type: object
    properties:
      Age:
        description: 年龄
        type: string
      CreatedAt:
        description: 创建时间
        type: integer
        format: int64
      Email:
        description: 邮箱
        type: string
      Game:
        description: 游戏
        type: string
      Id:
        type: integer
        format: int64
      Region:
        description: 地区/国家
        type: string
      Sexuality:
        description: 0 女 1 男 2保密
        type: integer
        format: int32
      Suggest:
        description: 建议
        type: string
  models.age:
    title: age
    type: object
  models.email:
    title: email
    type: object
  models.game:
    title: game
    type: object
  models.region:
    title: region
    type: object
  models.sexuality:
    title: sexuality
    type: object
  models.suggest:
    title: suggest
    type: object
tags:
- name: driver_survey
  description: |
    DriverSurveyController operations for DriverSurvey
